version: '3.8'
services:
  database:
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - my_data:/data/db
  backend:
    depends_on:
      - database
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=database
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    volumes:
      - ./backend:/backend
volumes:
  my_data:
