version: '3.8'
services:
  database:
    image: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - my_data:/data/db
  backend:
    depends_on:
      - database
    restart: unless-stopped
    build: ./backend
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - '9229:9229'
    environment:
      - DB_HOST=database
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_PROTOCOL=mongodb
      - NODE_DOCKER_PORT=$NODE_DOCKER_PORT
    volumes:
      - ./backend:/backend
  frontend:
    depends_on:
      - backend
    restart: unless-stopped
    build: ./frontend
    env_file: .env
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./frontend:/frontend
volumes:
  my_data:
